	db {sprite_tile_0}, {sprite_tile_0}
	db {sprite_tile_0}, {sprite_tile_1}
	db {sprite_tile_0}, {sprite_tile_2}
	db {sprite_tile_0}, {sprite_tile_3}
	db {sprite_tile_0}, {sprite_tile_4}
	db {sprite_tile_0}, {sprite_tile_5}
	db {sprite_tile_0}, {sprite_tile_6}
	db {sprite_tile_0}, {sprite_tile_7}
	db {sprite_tile_0}, {sprite_tile_8}
	db {sprite_tile_0}, {sprite_tile_9}
	db {sprite_tile_1}, {sprite_tile_0}
	db {sprite_tile_1}, {sprite_tile_1}
	db {sprite_tile_1}, {sprite_tile_2}
	db {sprite_tile_1}, {sprite_tile_3}
	db {sprite_tile_1}, {sprite_tile_4}
	db {sprite_tile_1}, {sprite_tile_5}
	db {sprite_tile_1}, {sprite_tile_6}
	db {sprite_tile_1}, {sprite_tile_7}
	db {sprite_tile_1}, {sprite_tile_8}
	db {sprite_tile_1}, {sprite_tile_9}
	db {sprite_tile_2}, {sprite_tile_0}
	db {sprite_tile_2}, {sprite_tile_1}
	db {sprite_tile_2}, {sprite_tile_2}
	db {sprite_tile_2}, {sprite_tile_3}
	db {sprite_tile_2}, {sprite_tile_4}
	db {sprite_tile_2}, {sprite_tile_5}
	db {sprite_tile_2}, {sprite_tile_6}
	db {sprite_tile_2}, {sprite_tile_7}
	db {sprite_tile_2}, {sprite_tile_8}
	db {sprite_tile_2}, {sprite_tile_9}
	db {sprite_tile_3}, {sprite_tile_0}
	db {sprite_tile_3}, {sprite_tile_1}
	db {sprite_tile_3}, {sprite_tile_2}
	db {sprite_tile_3}, {sprite_tile_3}
	db {sprite_tile_3}, {sprite_tile_4}
	db {sprite_tile_3}, {sprite_tile_5}
	db {sprite_tile_3}, {sprite_tile_6}
	db {sprite_tile_3}, {sprite_tile_7}
	db {sprite_tile_3}, {sprite_tile_8}
	db {sprite_tile_3}, {sprite_tile_9}
	db {sprite_tile_4}, {sprite_tile_0}
	db {sprite_tile_4}, {sprite_tile_1}
	db {sprite_tile_4}, {sprite_tile_2}
	db {sprite_tile_4}, {sprite_tile_3}
	db {sprite_tile_4}, {sprite_tile_4}
	db {sprite_tile_4}, {sprite_tile_5}
	db {sprite_tile_4}, {sprite_tile_6}
	db {sprite_tile_4}, {sprite_tile_7}
	db {sprite_tile_4}, {sprite_tile_8}
	db {sprite_tile_4}, {sprite_tile_9}
	db {sprite_tile_5}, {sprite_tile_0}
	db {sprite_tile_5}, {sprite_tile_1}
	db {sprite_tile_5}, {sprite_tile_2}
	db {sprite_tile_5}, {sprite_tile_3}
	db {sprite_tile_5}, {sprite_tile_4}
	db {sprite_tile_5}, {sprite_tile_5}
	db {sprite_tile_5}, {sprite_tile_6}
	db {sprite_tile_5}, {sprite_tile_7}
	db {sprite_tile_5}, {sprite_tile_8}
	db {sprite_tile_5}, {sprite_tile_9}
	db {sprite_tile_6}, {sprite_tile_0}
	db {sprite_tile_6}, {sprite_tile_1}
	db {sprite_tile_6}, {sprite_tile_2}
	db {sprite_tile_6}, {sprite_tile_3}
	db {sprite_tile_6}, {sprite_tile_4}
	db {sprite_tile_6}, {sprite_tile_5}
	db {sprite_tile_6}, {sprite_tile_6}
	db {sprite_tile_6}, {sprite_tile_7}
	db {sprite_tile_6}, {sprite_tile_8}
	db {sprite_tile_6}, {sprite_tile_9}
	db {sprite_tile_7}, {sprite_tile_0}
	db {sprite_tile_7}, {sprite_tile_1}
	db {sprite_tile_7}, {sprite_tile_2}
	db {sprite_tile_7}, {sprite_tile_3}
	db {sprite_tile_7}, {sprite_tile_4}
	db {sprite_tile_7}, {sprite_tile_5}
	db {sprite_tile_7}, {sprite_tile_6}
	db {sprite_tile_7}, {sprite_tile_7}
	db {sprite_tile_7}, {sprite_tile_8}
	db {sprite_tile_7}, {sprite_tile_9}
	db {sprite_tile_8}, {sprite_tile_0}
	db {sprite_tile_8}, {sprite_tile_1}
	db {sprite_tile_8}, {sprite_tile_2}
	db {sprite_tile_8}, {sprite_tile_3}
	db {sprite_tile_8}, {sprite_tile_4}
	db {sprite_tile_8}, {sprite_tile_5}
	db {sprite_tile_8}, {sprite_tile_6}
	db {sprite_tile_8}, {sprite_tile_7}
	db {sprite_tile_8}, {sprite_tile_8}
	db {sprite_tile_8}, {sprite_tile_9}
	db {sprite_tile_9}, {sprite_tile_0}
	db {sprite_tile_9}, {sprite_tile_1}
	db {sprite_tile_9}, {sprite_tile_2}
	db {sprite_tile_9}, {sprite_tile_3}
	db {sprite_tile_9}, {sprite_tile_4}
	db {sprite_tile_9}, {sprite_tile_5}
	db {sprite_tile_9}, {sprite_tile_6}
	db {sprite_tile_9}, {sprite_tile_7}
	db {sprite_tile_9}, {sprite_tile_8}
	db {sprite_tile_9}, {sprite_tile_9}
